### ISSUE TITLE
OSoC - Create a basic popup UI for the extension

### ISSUE THREAD

**Issue by NavySaw23** [upes-open/OSoC-Advanced-Video-Controller-Extension#1]
Set up a simple HTML/CSS layout for the extension's popup. It should include the following components - 
- Name and logo of Extension
- A volume slider going from 0 to 200%
- A button to turn OCR on and off
- A button for picture in picture

> Note - Make sure that the UI collapses itself after the user clicks outside the popup.

**Comment by divyansh2375** [comment]
should we have to put any logo aur you have designed already any particular logo

**Comment by NavySaw23** [comment]
There is a logo file included as logo.png

**Comment by virajp4** [comment]
hi, I would like to take up this issue..

**Comment by NavySaw23** [comment]
Hi Viraj, the issue has been assigned to you!
