### ISSUE TITLE
OSoC - Develop custom video controls for YouTube Shorts

### ISSUE THREAD

**Issue by NavySaw23** [upes-open/OSoC-Advanced-Video-Controller-Extension#10]
Create functionality for YouTube Shorts videos, allowing users to skip forward and backward by a margin of 5 seconds. Also a toggle for auto-scrolling through Shorts.
Set key-binds for all of those functionalities.

**Comment by virajp4** [comment]
i would like to take this up

**Comment by NavySaw23** [comment]
@virajp4 Issue has been assigned

**Comment by virajp4** [comment]
the PRs mentioned above fix this issue.
