### ISSUE TITLE
Improve the readme.md file

### ISSUE THREAD

**Issue by karthiknadar1204** [upes-open/OSoC-Advanced-Video-Controller-Extension#15]
Here i propose to make the readme elaborate by adding an elaborate way to open a pr and set up the project as well as shell commands so that anyone starting out with the project can start out easily

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under osoc'23

**Comment by NavySaw23** [comment]
Hello Kartik! Thanks for your proposition. However, readme updates do not count as a contribution towards the progress of project completion. They are designed a certain way by the heads, for consistency across the projects.
Also, we have decided that the readme has to be updated toward the end of the project, as it will include UI screenshots. Hence I cannot assign this issue to you currently.
