### ISSUE TITLE
OSoC - Implement video speed up/down functionality.

### ISSUE THREAD

**Issue by NavySaw23** [upes-open/OSoC-Advanced-Video-Controller-Extension#2]
Add a button in the extension UI to toggle video speed. Ensure that clicking the button speeds up or slows down the video accordingly.
> Speed should range from 0.1x - 5x, in increments of 0.1
> i.e. 0.1x, 0.2x, 0.3x...

**Comment by tarunvenkat** [comment]
Hey @NavySaw23 Can I work on this issue?

**Comment by NavySaw23** [comment]
Hey Tarun! I appreciate your enthusiasm, you can start working on the issue

**Comment by virajp4** [comment]
hey, can i work on this?

**Comment by NavySaw23** [comment]
@virajp4 Issue has been assigned
